# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About Me
    url: '#about'
    weight: 10
  - name: Research
    url: '#research'
    weight: 20
  - name: CV
    url: 'files/OmarAshour_Berkeley_CV.pdf'
    weight: 30
  - name: Academic Resume
    url: 'files/OmarAshour_Berkeley_AcademicResume.pdf'
  - name: Industry Resume
    url: 'files/OmarAshour_Berkeley_IndustryResume.pdf'
    weight: 40
  - name: Notes
    url: 'https://ashour.dev'
    weight: 50

  #- name: Posts
  #  url: '#posts'
  #  weight: 20
  #- name: Projects
  #  url: '#projects'
  #  weight: 30
  #- name: Talks
  #  url: '#talks'
  #  weight: 40
  #- name: Publications
  #  url: '#featured'
  #  weight: 50
  #- name: Contact
  #  url: '#contact'
  #  weight: 60
