# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: '#about'
    weight: 10
  - name: Research
    url: '#research'
    weight: 20
  - name: Publications
    url: '#publications'
    weight: 30
  - name: CV
    identifier: cv
    url: 'files/OmarAshour_Berkeley_CV.pdf'
    weight: 40
  - name: Résumé
    identifier: resume
    weight: 40
    url: 'files/OmarAshour_Berkeley_Resume.pdf'
  #- name: Academic
  #  parent: resume
  #  url: 'files/OmarAshour_Berkeley_AcademicResume.pdf'
  #  weight: 1
  #- name: Industry
  #  parent: resume
  #  url: 'files/OmarAshour_Berkeley_IndustryResume.pdf'
  #  weight: 2
  - name: Digital Garden
    url: 'https://ashour.dev'
    weight: 50

  #- name: Posts
  #  url: '#posts'
  #  weight: 20
  #- name: Projects
  #  url: '#projects'
  #  weight: 30
  #- name: Talks
  #  url: '#talks'
  #  weight: 40
  #- name: Publications
  #  url: '#featured'
  #  weight: 50
  #- name: Contact
  #  url: '#contact'
  #  weight: 60
